# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f75ade9ec91bf209f2fa1a656229a80112d9e2df189f6be240b639ccc6ec2500c46a8030c36de30cd687525fdafea1e36fc24ca2b037938534b7cc2caa0386ac

test:
  secret_key_base: f2423359385b5e8c0a729fde3583b2447c39961c8482a2bfcb5c8dd41f73a9b39c9e0dc24e92dbd472fe4e5ccdbb345a171de2b07b1cbea66fada5b5655fa05b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
